# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
print("NumPy version:", np.__version__)
print("\nNumPy configuration:")
np.show_config()

NumPy version: 1.22.4

NumPy configuration:
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language 

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [4]:
arr = np.zeros((3, 4))
size_in_bytes = arr.nbytes

print("Array size in bytes:", size_in_bytes)

Array size in bytes: 96


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [5]:
np.info()

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x7fa6d83a2700>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +SKIP

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [6]:
null_vector = np.zeros(10)
null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [7]:
vector = np.arange(10, 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [8]:
vector = np.array([1, 2, 3, 4, 5])

reversed_vector = vector[::-1]

print(reversed_vector)

[5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [9]:
values = np.arange(0, 9)
matrix = values.reshape(3, 3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [10]:
array = np.array([1, 2, 0, 0, 4, 0])
nonzero_indices = np.nonzero(array)

print(nonzero_indices)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [11]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [12]:
arr = np.random.rand(3, 3, 3)
print(arr)

[[[0.57125451 0.00702212 0.33681511]
  [0.70315653 0.58621601 0.76969368]
  [0.0554843  0.39160846 0.44515224]]

 [[0.21956492 0.11363935 0.84309016]
  [0.3314611  0.63109505 0.81373094]
  [0.28114585 0.24063382 0.09157895]]

 [[0.99933963 0.56047024 0.62728801]
  [0.62566883 0.05116403 0.74706307]
  [0.48691797 0.04641597 0.4303064 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [13]:
print(arr)

min_value = np.min(arr)
max_value = np.max(arr)

print("Minimum value:", min_value)
print("Maximum value:", max_value)

[[[0.57125451 0.00702212 0.33681511]
  [0.70315653 0.58621601 0.76969368]
  [0.0554843  0.39160846 0.44515224]]

 [[0.21956492 0.11363935 0.84309016]
  [0.3314611  0.63109505 0.81373094]
  [0.28114585 0.24063382 0.09157895]]

 [[0.99933963 0.56047024 0.62728801]
  [0.62566883 0.05116403 0.74706307]
  [0.48691797 0.04641597 0.4303064 ]]]
Minimum value: 0.007022122285110233
Maximum value: 0.9993396260070225


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [14]:
vec = np.random.rand(30)
print(vec)

mean_value = np.mean(vec)
print("Mean value:", mean_value)

[0.41310116 0.21136084 0.68928803 0.72749634 0.38091811 0.12187512
 0.57317607 0.29858933 0.38304863 0.36185281 0.03284673 0.00972537
 0.27971968 0.26016949 0.65626008 0.16038722 0.52987586 0.47255813
 0.27471849 0.15874043 0.75061062 0.85238629 0.6421691  0.55357215
 0.06941467 0.32533175 0.29232047 0.99711269 0.65870656 0.55534722]
Mean value: 0.4230893149129717


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [16]:
rows = 5
cols = 5
arr = np.zeros((rows, cols))
arr[0,:] = 1
arr[rows-1,:] = 1
arr[:,0] = 1
arr[:,cols-1] = 1

print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
border_size = 1

padded_arr = np.pad(arr, pad_width=border_size, mode='constant', constant_values=0)

print(padded_arr)

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [18]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [19]:
matrix = np.zeros((5, 5))
np.fill_diagonal(matrix[1:], [1, 2, 3, 4])

print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [20]:
matrix = np.zeros((8, 8), dtype=int)
matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1

print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [21]:
arr = np.random.rand(6, 7, 8)
index_1d = 100
index_3d = np.unravel_index(index_1d, shape=arr.shape)

print(index_3d)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [22]:
checkerboard = np.array([[0, 1], [1, 0]])
matrix = np.tile(checkerboard, (4, 4))

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [23]:
matrix = np.random.rand(5, 5)
matrix_normalized = matrix / np.max(matrix)

print(matrix_normalized)

[[1.         0.99834348 0.6166852  0.59854603 0.89143438]
 [0.47465499 0.95823596 0.39626206 0.03366354 0.34649676]
 [0.42653551 0.03756819 0.28599617 0.48029065 0.14410529]
 [0.20914141 0.59101379 0.71468021 0.38125239 0.8790856 ]
 [0.93316199 0.42282948 0.66160518 0.03990749 0.03490239]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [24]:
color_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])
color = np.array((255, 0, 0, 255), dtype=color_dtype)

print(color)

(255, 0, 0, 255)


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [25]:
matrix1 = np.random.rand(5, 3)
matrix2 = np.random.rand(3, 2)
product = np.dot(matrix1, matrix2)

print(product)

[[0.88857862 0.98595063]
 [0.55800054 0.53735743]
 [0.25244207 0.32335161]
 [0.32109139 0.27801825]
 [0.48931295 0.31083992]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [27]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[(arr > 3) & (arr <= 8)] *= -1

print(arr)

[ 0  1  2  3 -4 -5 -6 -7 -8  9]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [11]:
'''Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
are all legal'''


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [28]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-28-cd809174da5d>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
<ipython-input-28-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [29]:
arr = np.random.uniform(-5, 5, 10)
arr_rounded = np.ceil(np.abs(arr)) * np.copysign(1, arr)

print(arr)
print(arr_rounded)

[-1.70300031  1.21299589  2.90745259  3.33378979  1.76328177 -1.03465226
 -4.63588226 -0.57429535 -0.79281812 -4.16585227]
[-2.  2.  3.  4.  2. -2. -5. -1. -1. -5.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [30]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])
common = np.intersect1d(arr1, arr2)

print(common)

[3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [31]:
np.seterr(all='ignore')
with np.errstate():
    pass

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [32]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [33]:
today = np.datetime64('today')

yesterday = today - np.timedelta64(1, 'D')

tomorrow = today + np.timedelta64(1, 'D')

print(yesterday, today, tomorrow)

2023-02-28 2023-03-01 2023-03-02


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [34]:
start = np.datetime64('2016-07-01')
days_in_month = np.datetime64('2016-08-01') - start

dates = np.arange(start, start + days_in_month, np.timedelta64(1, 'D'))

print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [36]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

np.add(A, B, out=B)
np.negative(A, out=A)
# np.divide(A, 2, out=A)
np.multiply(A, B, out=B)

print(B)

[ -5 -14 -27]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [37]:
arr = np.random.uniform(-10, 10, size=(5,))
integer_part = arr // 1 

print(integer_part)

[5. 8. 3. 3. 4.]


In [38]:
arr = np.random.uniform(-10, 10, size=(5,))
integer_part = np.floor(arr)

print(integer_part)

[ 9. -4. -5. -3. -4.]


In [39]:
arr = np.random.uniform(-10, 10, size=(5,))
integer_part = np.ceil(arr) - 1

print(integer_part)

[  4.   0.  -7. -10.   7.]


In [40]:
arr = np.random.uniform(-10, 10, size=(5,))
integer_part = arr.astype(int)

print(integer_part)

[ 3 -5 -6  2 -5]


In [41]:
arr = np.random.uniform(-10, 10, size=(5,))
integer_part = np.trunc(arr)

print(integer_part)

[ 4.  7. -4.  2. -2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [42]:
arr = np.arange(5)
mat = np.tile(arr, (5, 1))

print(mat)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [43]:
def my_generator():
    for i in range(10):
        yield i

arr = np.fromiter(my_generator(), dtype=int)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [44]:
vec = np.linspace(0, 1, num=10, endpoint=False)

print(vec)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [45]:
v = np.random.rand(10)

v_sorted = np.sort(v)

print(v_sorted)

[0.05366928 0.10759441 0.19301017 0.26253035 0.27382979 0.34591577
 0.37870086 0.47870748 0.55114555 0.92494332]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [46]:
a = np.array([1, 2, 3, 4, 5])

sum_a = np.add.reduce(a)

print(sum_a)

15


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [47]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

if np.array_equal(A, B):
    print("The arrays A and B are equal")
else:
    print("The arrays A and B are not equal")

The arrays A and B are not equal


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [48]:
arr = np.array([1, 2, 3, 4, 5])
arr.flags.writeable = False

arr[0] = 10 

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [49]:
cartesian = np.random.random((10, 2))

# Compute radial distance
r = np.sqrt(np.sum(cartesian**2, axis=1))

# Compute angle
theta = np.arctan2(cartesian[:,1], cartesian[:,0])

# Convert angle to degrees
theta_degrees = np.rad2deg(theta)

# Create polar coordinates matrix
polar = np.column_stack((r, theta_degrees))

print(polar)

[[ 0.63303536  0.5802378 ]
 [ 0.17435929  3.95094917]
 [ 0.552385   61.23275417]
 [ 1.0662376  67.2423592 ]
 [ 1.31777408 45.87390483]
 [ 0.99469385 30.33013054]
 [ 1.21414562 50.66475415]
 [ 1.09713666 31.15696392]
 [ 0.94146669  0.4254001 ]
 [ 1.21393956 38.18148782]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [51]:
v = np.random.rand(10)

# Find the index of the maximum value
max_idx = np.argmax(v)

# Replace the maximum value by 0
v[max_idx] = 0

print(v)

[0.64257486 0.74888728 0.81022233 0.60425462 0.87082267 0.98237271
 0.30552034 0.         0.51018985 0.60602582]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [52]:
import numpy as np

X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])
C = 1 / np.subtract.outer(X, Y)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [53]:
dtypes = ['int8', 'int16', 'int32', 'int64', 'float16', 'float32', 'float64', 'complex64', 'complex128']

for dtype in dtypes:
    info = np.iinfo(dtype) if 'int' in dtype else np.finfo(dtype)
    print(dtype, info.min, info.max)

int8 -128 127
int16 -32768 32767
int32 -2147483648 2147483647
int64 -9223372036854775808 9223372036854775807
float16 -65500.0 65500.0
float32 -3.4028235e+38 3.4028235e+38
float64 -1.7976931348623157e+308 1.7976931348623157e+308
complex64 -3.4028235e+38 3.4028235e+38
complex128 -1.7976931348623157e+308 1.7976931348623157e+308


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [54]:
print("Integer types:")
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    info = np.iinfo(dtype)
    print(f"{dtype}: min={info.min}, max={info.max}")
    
# Floating-point types
print("\nFloating-point types:")
for dtype in [np.float16, np.float32, np.float64]:
    info = np.finfo(dtype)
    print(f"{dtype}: min={info.min}, max={info.max}, eps={info.eps}")

Integer types:
<class 'numpy.int8'>: min=-128, max=127
<class 'numpy.int16'>: min=-32768, max=32767
<class 'numpy.int32'>: min=-2147483648, max=2147483647
<class 'numpy.int64'>: min=-9223372036854775808, max=9223372036854775807

Floating-point types:
<class 'numpy.float16'>: min=-65504.0, max=65504.0, eps=0.0009765625
<class 'numpy.float32'>: min=-3.4028234663852886e+38, max=3.4028234663852886e+38, eps=1.1920928955078125e-07
<class 'numpy.float64'>: min=-1.7976931348623157e+308, max=1.7976931348623157e+308, eps=2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [55]:
arr = np.random.rand(5, 5)
np.set_printoptions(threshold=np.inf)
print(arr)

[[0.77071232 0.71338181 0.47369956 0.85546526 0.61919828]
 [0.08575047 0.78669943 0.19183529 0.0575159  0.75838533]
 [0.99499705 0.55218404 0.99240205 0.80623383 0.76771885]
 [0.8894936  0.96754302 0.31000336 0.24402071 0.67722197]
 [0.48211438 0.1276635  0.53507127 0.82382163 0.68586855]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [56]:
x = np.random.rand(10)
y = 0.5

index = np.abs(x - y).argmin()

print("Closest value to {} is {}".format(y, x[index]))

Closest value to 0.5 is 0.49617379800538963


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)